server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com # 修改eureka上默认的描述信息
    prefer-ip-address: true

# info配置
info:
  app.name: kuangshen-springcloud
  company.name: blog.kuangstudy.com

# zuul 路由网关
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/** # 将真是路径隐藏为/mydept/**
  ignored-services: "*" # 不能再使用原来的真实路径访问了